name: Envoi vers la Forge

# Quand est-ce que le robot s'active ? 
# Réponse : À chaque fois que tu envoies du code sur la branche "main"
on:
  push:
    branches:
      - main 

jobs:
  synchroniser:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Récupérer le code depuis GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Permet de copier tout l'historique de ton projet

      - name: 2. Envoyer le code vers la Forge
        # C'est ici que la magie opère ! Remplace les MAJUSCULES par tes informations :
        run: |
          git remote add forge https://dziubanowskicedric:${{ secrets.JETON_FORGE }}@forge.education.gouv.fr/widgets-grist-cd/public/github.git
          git push forge main
